language: python

python:
  - "2.7"

install:
  - travis_retry pip install -r dev-requirements.txt
  - travis_retry pip install coveralls

before_script:
  - flake8 .
  - API_CHECK=https://appengine.google.com/api/updatecheck
  - SDK_VERSION=$(curl -s $API_CHECK | awk -F '\"' '/release/ {print $2}')
  - SDK_URL=https://storage.googleapis.com/appengine-sdks/featured/google_appengine_$SDK_VERSION.zip
  - wget $SDK_URL -nv
  - unzip -q google_appengine_$SDK_VERSION.zip
  - export PYTHONPATH=${PYTHONPATH}:${PWD}/google_appengine

script:
  - coverage run --source=. setup.py test

after_success:
  - coveralls
